### ISSUE TITLE
Jetbot breaks with JetPack 4.3/TensorFlow 2.0

### ISSUE THREAD

**Issue by skarlekar** [NVIDIA-AI-IOT/jetbot#173]
I recently upgraded my _Jetbot_ to _**JetPack 4.3**_ using the instructions at [https://github.com/NVIDIA-AI-IOT/jetbot/wiki/Create-SD-Card-Image-From-Scratch](https://github.com/NVIDIA-AI-IOT/jetbot/wiki/Create-SD-Card-Image-From-Scratch) to use TensorFlow 2.0 for a project. 

Unfortunately after a long installation process, I find that _jetbot_ is broken in _JetPack 4.3_. When I try to use any classes in _jetbot_, it internally imports _tensorflow.NodeDef_ which does not seem to work in TensorFlow 2.0 and fails with the error message:

`ImportError: cannot import name 'NodeDef'`

Note that, JetPack 4.3 comes with TensorFlow 2.0

Please see the snapshot of error message below. My TensorFlow and JetPack environment is as follows. 

**Does any solution exist to resolve this issue?** 
**When is Jetbot going to be upgraded to JetPack 4.3?**

Any thoughts or solutions will be much appreciated. I cannot drop the TensorFlow to previous version as I have to use version 2.0 for my project.

**JetPack version:**

```
jetbot@jetbot-desktop:~/Notebooks/my_collision_avoidance$ JETSON_L4T_STRING=$(head -n 1 /etc/nv_tegra_release)
jetbot@jetbot-desktop:~/Notebooks/my_collision_avoidance$ JETSON_L4T_RELEASE=$(echo $JETSON_L4T_STRING | cut -f 2 -d ' ' | grep -Po '(?<=R)[^;]+')
jetbot@jetbot-desktop:~/Notebooks/my_collision_avoidance$ JETSON_L4T_REVISION=$(echo $JETSON_L4T_STRING | cut -f 2 -d ',' | grep -Po '(?<=REVISION: )[^;]+')
jetbot@jetbot-desktop:~/Notebooks/my_collision_avoidance$ JETSON_L4T_VERSION="$JETSON_L4T_RELEASE.$JETSON_L4T_REVISION"
jetbot@jetbot-desktop:~/Notebooks/my_collision_avoidance$ echo "$LOG Jetson BSP Version:  L4T R$JETSON_L4T_VERSION"
 Jetson BSP Version:  L4T R32.3.1
jetbot@jetbot-desktop:~/Notebooks/my_collision_avoidance$
```
**Error screenshot:**

![image](https://user-images.githubusercontent.com/3195548/71737448-ab3e3280-2e21-11ea-8de5-1a870d73048c.png)

**Comment by Xin20** [comment]
don't import Camera from jetbot, just import Camera. Same to bgr8_to_jpeg
